#!/bin/bash
#SBATCH -J my_LCS
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -p shared
#SBATCH -t 5:00:00
#SBATCH --mem-per-cpu 55G
#SBATCH -o ./slurm/lcs.%a.out
#SBATCH -e ./slurm/lcs.%a.err
#SBATCH --mail-user=ellen_considine@g.harvard.edu
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#
source ~/.bashrc
module load R/4.0.2-fasrc01
export R_LIBS_USER=$HOME/apps/R_4-0-2:$R_LIBS_USER
R CMD BATCH LCS_placement_sims/Analysis/Run_sims_split-up.R LCS_${SLURM_ARRAY_TASK_ID}.Rout
